// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB5BQOWA-lRh7_XuRXCnvug5Eg5Qx0CPM',
    appId: '1:546797918733:web:2006800b920bea3b969344',
    messagingSenderId: '546797918733',
    projectId: 'locum-c64b2',
    authDomain: 'locum-c64b2.firebaseapp.com',
    storageBucket: 'locum-c64b2.firebasestorage.app',
    measurementId: 'G-N25MJXK2ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiAPlz93WMX_EMaMqcVK1--m_suANgyIA',
    appId: '1:546797918733:android:227c3c89e7e73506969344',
    messagingSenderId: '546797918733',
    projectId: 'locum-c64b2',
    storageBucket: 'locum-c64b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO350XvNXtRPHi6YQ1A4irG_qXDEt3xjw',
    appId: '1:546797918733:ios:a005113f42b550dd969344',
    messagingSenderId: '546797918733',
    projectId: 'locum-c64b2',
    storageBucket: 'locum-c64b2.firebasestorage.app',
    iosBundleId: 'com.example.locume',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO350XvNXtRPHi6YQ1A4irG_qXDEt3xjw',
    appId: '1:546797918733:ios:a005113f42b550dd969344',
    messagingSenderId: '546797918733',
    projectId: 'locum-c64b2',
    storageBucket: 'locum-c64b2.firebasestorage.app',
    iosBundleId: 'com.example.locume',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB5BQOWA-lRh7_XuRXCnvug5Eg5Qx0CPM',
    appId: '1:546797918733:web:da96cccdbb3e6997969344',
    messagingSenderId: '546797918733',
    projectId: 'locum-c64b2',
    authDomain: 'locum-c64b2.firebaseapp.com',
    storageBucket: 'locum-c64b2.firebasestorage.app',
    measurementId: 'G-RKYKRNK1K3',
  );
}
